name 'ops-db-install'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ops-db-install'
long_description 'Installs/Configures ops-db-install'
version '0.1.0'

depends 'yum-epel', '~> 0.6.2'
depends 'rbac', '~> 1.0.3'
depends 'smf', '~> 2.2.7'
depends 'yum', '~> 3.6.3'
depends 'yum-mysql-community', '~> 0.1.17'
depends 'mysql', '~> 6.0.31'
depends 'mariadb', '~> 0.3.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'chef-sugar', '~> 3.1.1'
depends 'apt', '~> 2.7.0'
depends 'build-essential', '~> 2.2.3'
depends 'openssl', '~> 4.0.0'
depends 'postgresql', '~> 3.4.20'
depends 'database', '~> 4.0.6'
